from sqlalchemy import BigInteger, Double, Text, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class GTDBMetadata(Base):
    __tablename__ = "gtdb_metadata"

    version: Mapped[str] = mapped_column(String(20), primary_key=True)
    accession: Mapped[str] = mapped_column(String(30), primary_key=True)

    ambiguous_bases: Mapped[int | None] = mapped_column(BigInteger)
    checkm2_completeness: Mapped[float | None] = mapped_column(Double)
    checkm2_contamination: Mapped[float | None] = mapped_column(Double)
    checkm2_model: Mapped[str | None] = mapped_column(String(50))
    checkm_completeness: Mapped[float | None] = mapped_column(Double)
    checkm_contamination: Mapped[float | None] = mapped_column(Double)
    checkm_marker_count: Mapped[int | None] = mapped_column(BigInteger)
    checkm_marker_lineage: Mapped[str | None] = mapped_column(Text)
    checkm_marker_set_count: Mapped[int | None] = mapped_column(BigInteger)
    checkm_strain_heterogeneity: Mapped[float | None] = mapped_column(Double)

    coding_bases: Mapped[int | None] = mapped_column(BigInteger)
    coding_density: Mapped[float | None] = mapped_column(Double)
    contig_count: Mapped[int | None] = mapped_column(BigInteger)
    gc_count: Mapped[int | None] = mapped_column(BigInteger)
    gc_percentage: Mapped[float | None] = mapped_column(Double)
    genome_size: Mapped[int | None] = mapped_column(BigInteger)

    gtdb_genome_representative: Mapped[str | None] = mapped_column(Text)
    gtdb_representative: Mapped[str | None] = mapped_column(Text)
    gtdb_taxonomy: Mapped[str | None] = mapped_column(Text)
    gtdb_type_designation_ncbi_taxa: Mapped[str | None] = mapped_column(Text)
    gtdb_type_designation_ncbi_taxa_sources: Mapped[str | None] = mapped_column(Text)
    gtdb_type_species_of_genus: Mapped[str | None] = mapped_column(Text)

    l50_contigs: Mapped[int | None] = mapped_column(BigInteger)
    l50_scaffolds: Mapped[int | None] = mapped_column(BigInteger)
    longest_contig: Mapped[int | None] = mapped_column(BigInteger)
    longest_scaffold: Mapped[int | None] = mapped_column(BigInteger)

    lsu_23s_contig_len: Mapped[str | None] = mapped_column(Text)
    lsu_23s_count: Mapped[int | None] = mapped_column(BigInteger)
    lsu_23s_length: Mapped[str | None] = mapped_column(Text)
    lsu_23s_query_id: Mapped[str | None] = mapped_column(Text)

    lsu_5s_contig_len: Mapped[str | None] = mapped_column(Text)
    lsu_5s_count: Mapped[int | None] = mapped_column(BigInteger)
    lsu_5s_length: Mapped[str | None] = mapped_column(Text)
    lsu_5s_query_id: Mapped[str | None] = mapped_column(Text)

    lsu_silva_23s_blast_align_len: Mapped[str | None] = mapped_column(Text)
    lsu_silva_23s_blast_bitscore: Mapped[str | None] = mapped_column(Text)
    lsu_silva_23s_blast_evalue: Mapped[str | None] = mapped_column(Text)
    lsu_silva_23s_blast_perc_identity: Mapped[str | None] = mapped_column(Text)
    lsu_silva_23s_blast_subject_id: Mapped[str | None] = mapped_column(Text)
    lsu_silva_23s_taxonomy: Mapped[str | None] = mapped_column(Text)

    mean_contig_length: Mapped[int | None] = mapped_column(BigInteger)
    mean_scaffold_length: Mapped[int | None] = mapped_column(BigInteger)

    mimag_high_quality: Mapped[str | None] = mapped_column(Text)
    mimag_low_quality: Mapped[str | None] = mapped_column(Text)
    mimag_medium_quality: Mapped[str | None] = mapped_column(Text)

    n50_contigs: Mapped[int | None] = mapped_column(BigInteger)
    n50_scaffolds: Mapped[int | None] = mapped_column(BigInteger)

    ncbi_assembly_level: Mapped[str | None] = mapped_column(Text)
    ncbi_assembly_name: Mapped[str | None] = mapped_column(Text)
    ncbi_assembly_type: Mapped[str | None] = mapped_column(Text)
    ncbi_bioproject: Mapped[str | None] = mapped_column(Text)
    ncbi_biosample: Mapped[str | None] = mapped_column(Text)
    ncbi_contig_count: Mapped[str | None] = mapped_column(Text)
    ncbi_contig_n50: Mapped[str | None] = mapped_column(Text)
    ncbi_country: Mapped[str | None] = mapped_column(Text)
    ncbi_date: Mapped[str | None] = mapped_column(Text)
    ncbi_genbank_assembly_accession: Mapped[str | None] = mapped_column(Text)
    ncbi_genome_category: Mapped[str | None] = mapped_column(Text)
    ncbi_genome_representation: Mapped[str | None] = mapped_column(Text)
    ncbi_isolate: Mapped[str | None] = mapped_column(Text)
    ncbi_isolation_source: Mapped[str | None] = mapped_column(Text)
    ncbi_lat_lon: Mapped[str | None] = mapped_column(Text)
    ncbi_molecule_count: Mapped[int | None] = mapped_column(BigInteger)
    ncbi_ncrna_count: Mapped[str | None] = mapped_column(Text)
    ncbi_organism_name: Mapped[str | None] = mapped_column(Text)
    ncbi_protein_count: Mapped[str | None] = mapped_column(Text)
    ncbi_refseq_category: Mapped[str | None] = mapped_column(Text)
    ncbi_rrna_count: Mapped[str | None] = mapped_column(Text)
    ncbi_scaffold_count: Mapped[str | None] = mapped_column(Text)
    ncbi_scaffold_l50: Mapped[str | None] = mapped_column(Text)
    ncbi_scaffold_n50: Mapped[str | None] = mapped_column(Text)
    ncbi_scaffold_n75: Mapped[str | None] = mapped_column(Text)
    ncbi_scaffold_n90: Mapped[str | None] = mapped_column(Text)
    ncbi_seq_rel_date: Mapped[str | None] = mapped_column(Text)
    ncbi_spanned_gaps: Mapped[int | None] = mapped_column(BigInteger)
    ncbi_species_taxid: Mapped[int | None] = mapped_column(BigInteger)
    ncbi_ssu_count: Mapped[str | None] = mapped_column(Text)
    ncbi_strain_identifiers: Mapped[str | None] = mapped_column(Text)
    ncbi_submitter: Mapped[str | None] = mapped_column(Text)
    ncbi_taxid: Mapped[int | None] = mapped_column(BigInteger)
    ncbi_taxonomy: Mapped[str | None] = mapped_column(Text)
    ncbi_taxonomy_unfiltered: Mapped[str | None] = mapped_column(Text)
    ncbi_total_gap_length: Mapped[int | None] = mapped_column(BigInteger)
    ncbi_total_length: Mapped[int | None] = mapped_column(BigInteger)
    ncbi_translation_table: Mapped[str | None] = mapped_column(Text)
    ncbi_trna_count: Mapped[str | None] = mapped_column(Text)
    ncbi_type_material_designation: Mapped[str | None] = mapped_column(Text)
    ncbi_ungapped_length: Mapped[int | None] = mapped_column(BigInteger)
    ncbi_unspanned_gaps: Mapped[int | None] = mapped_column(BigInteger)
    ncbi_wgs_master: Mapped[str | None] = mapped_column(Text)

    protein_count: Mapped[int | None] = mapped_column(BigInteger)
    scaffold_count: Mapped[int | None] = mapped_column(BigInteger)

    ssu_contig_len: Mapped[str | None] = mapped_column(Text)
    ssu_count: Mapped[int | None] = mapped_column(BigInteger)
    ssu_gg_blast_align_len: Mapped[str | None] = mapped_column(Text)
    ssu_gg_blast_bitscore: Mapped[str | None] = mapped_column(Text)
    ssu_gg_blast_evalue: Mapped[str | None] = mapped_column(Text)
    ssu_gg_blast_perc_identity: Mapped[str | None] = mapped_column(Text)
    ssu_gg_blast_subject_id: Mapped[str | None] = mapped_column(Text)
    ssu_gg_taxonomy: Mapped[str | None] = mapped_column(Text)
    ssu_length: Mapped[str | None] = mapped_column(Text)
    ssu_query_id: Mapped[str | None] = mapped_column(Text)
    ssu_silva_blast_align_len: Mapped[str | None] = mapped_column(Text)
    ssu_silva_blast_bitscore: Mapped[str | None] = mapped_column(Text)
    ssu_silva_blast_evalue: Mapped[str | None] = mapped_column(Text)
    ssu_silva_blast_perc_identity: Mapped[str | None] = mapped_column(Text)
    ssu_silva_blast_subject_id: Mapped[str | None] = mapped_column(Text)
    ssu_silva_taxonomy: Mapped[str | None] = mapped_column(Text)

    total_gap_length: Mapped[int | None] = mapped_column(BigInteger)
    trna_aa_count: Mapped[int | None] = mapped_column(BigInteger)
    trna_count: Mapped[int | None] = mapped_column(BigInteger)
    trna_selenocysteine_count: Mapped[int | None] = mapped_column(BigInteger)
